export const ACTIONS = {
  SET_CART_ITEMS_COUNT: "SET_CART_ITEMS_COUNT",
  TRUE_OPEN_LOGIN:"TRUE_OPEN_LOGIN",
  FALSE_OPEN_LOGIN:"FALSE_OPEN_LOGIN",
  TRUE_OPEN_SEARCH:"TRUE_OPEN_SEARCH",
  FALSE_OPEN_SEARCH:"FALSE_OPEN_SEARCH",
  FALSE_IS_PAYMENT_METHOD_SELECTED:"FALSE_IS_PAYMENT_METHOD_SELECTED",
  TRUE_IS_PAYMENT_METHOD_SELECTED:"TRUE_IS_PAYMENT_METHOD_SELECTED",
  RELOAD_CART:"RELOAD_CART",
  TRUE_GLOBAL_USER_lOGIN:"TRUE_GLOBAL_USER_lOGIN",
  FALSE_GLOBAL_USER_lOGIN:"FALSE_GLOBAL_USER_lOGIN"
};